-- Supabase PostgreSQL Migration: Telemetry Alerts Table
-- Upstream: car-tracker backend
--
-- Automation event histories generated by the tracker.js engine.
-- Each row represents a single alert that was dispatched to
-- Telegram and optionally persisted here for audit/reporting.

CREATE TABLE IF NOT EXISTS telemetry_alerts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_type    TEXT NOT NULL DEFAULT 'message',
  message       TEXT NOT NULL,
  vehicle_id    TEXT,
  location      TEXT,
  speed         NUMERIC(6,2),
  fuel          NUMERIC(8,2),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for common query patterns
CREATE INDEX idx_telemetry_alerts_alert_type   ON telemetry_alerts (alert_type);
CREATE INDEX idx_telemetry_alerts_vehicle_id   ON telemetry_alerts (vehicle_id);
CREATE INDEX idx_telemetry_alerts_created_at   ON telemetry_alerts (created_at DESC);