ALTER TABLE scheduler_runs
  ADD COLUMN IF NOT EXISTS trigger_source TEXT NOT NULL DEFAULT 'cron',
  ADD COLUMN IF NOT EXISTS rows_examined INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS batch_offset INTEGER,
  ADD COLUMN IF NOT EXISTS batch_size INTEGER;

