export function mapGpsTripLogRow(row: any) {
  return {
    id: row.id ?? row.gps_id,
    gpsRecordNo: row.gps_record_no,
    tripDate: row.trip_date,
    toDate: row.scheduled_date || row.trip_date,
    vehicleId: row.vehicle_id,
    driverId: row.driver_id,
    originGpsStartPoint: row.origin_gps_start_point || '',
    destinationGpsEndPoint: row.destination_gps_end_point || '',
    coordinatesOrigin: row.coordinates_origin,
    coordinatesDestination: row.coordinates_destination,
    actualRouteRoadTaken: row.actual_route_road_taken || '',
    toOrigin: row.to_origin || null,
    toDestination: row.to_destination || null,
    departureTimeGps: row.departure_time_gps || null,
    arrivalTimeGps: row.arrival_time_gps || null,
    gpsDistanceKm: row.gps_distance_km,
    engineHours: row.engine_hours,
    maxSpeedKph: row.max_speed_kph,
    tripStatusGps: row.trip_status_gps,
    travelOrderId: row.travel_order_id || null,
    travelOrderStatus: row.to_status ?? null,
    toStatusAuto: row.to_status_auto ?? null,
    anomalyFlag: row.anomaly_flag,
    notesRemarks: row.notes_remarks || null,
    destinationVerified: row.destination_verified,
    tripType: row.trip_type,
    parentTripId: row.parent_trip_id,
    parentGpsRecordNo: row.parent_gps_record_no || null,
    pairedReturnId: row.paired_return_id || null,
    pairedReturnGpsRecordNo: row.paired_return_gps_record_no || null,
    locationName: row.location_name ?? row.latest_location ?? null,
    vehiclePlateNo: row.plate_number ?? 'Unknown',
    driverName: row.driver_full_name ?? 'Unknown',
    toNumber: row.travel_order_to_number ?? null,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    movingHours: row.moving_hours ?? null,
    telemetryCount: row.telemetry_count || 0,
    latestSpeed: row.latest_speed || null,
  };
}
